# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171115_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_set_own_password',
        ),
        migrations.AddField(
            model_name='user',
            name='activation_key',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
