# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171122_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberActivationEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Member Activation Email',
            },
        ),
    ]
