# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 12:13
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_memberactivationemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberactivationemail',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
