# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20171206_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberactivationemail',
            name='test_email_address',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
