# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_memberactivationemail_test_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberactivationemail',
            name='content',
        ),
        migrations.AddField(
            model_name='memberactivationemail',
            name='html_content',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AddField(
            model_name='memberactivationemail',
            name='text_content',
            field=models.TextField(default=''),
        ),
    ]
