# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20171211_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_key',
            field=models.CharField(default=users.models.activation_key_default, max_length=20),
        ),
    ]
