# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-08 15:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('html_content', tinymce.models.HTMLField(default='', help_text='Available place-holders: [name], [link], [months_since_launch] and [active_member_count].\nUse /static/mxv/images/logo.png as the URL of an image to insert the Momentum logo (just in the HTML content).')),
                ('text_content', models.TextField(default='', help_text='Available place-holders: [name], [link], [months_since_launch] and [active_member_count].')),
            ],
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_email_address', django.contrib.postgres.fields.citext.CIEmailField(default='', max_length=254)),
                ('send_count', models.PositiveIntegerField(default=1000)),
                ('is_active', models.BooleanField(default=False)),
                ('activation_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mxv.Email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', django.contrib.postgres.fields.citext.CIEmailField(max_length=255, unique=True)),
                ('sent', models.NullBooleanField(default=None)),
            ],
        ),
    ]
