# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-08 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mxv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='html_content',
            field=tinymce.models.HTMLField(default='', help_text='Available place-holders: [name], [link], [months_since_launch], [proposal_count] and [active_member_count]. Use /static/mxv/images/logo.png as the URL of an image to insert the Momentum logo.'),
        ),
        migrations.AlterField(
            model_name='email',
            name='text_content',
            field=models.TextField(default='', help_text='Available place-holders: [name], [link], [months_since_launch], [proposal_count] and [active_member_count]. '),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='activation_email',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mxv.Email'),
        ),
    ]
