# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-08 15:43
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mxv', '0002_auto_20180508_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='html_content',
            field=tinymce.models.HTMLField(default='', help_text='Available place-holders: [name], [link], [months_since_launch], [proposal_count] and [active_member_count]. Use https://d3n8a8pro7vhmx.cloudfront.net/momentum/pages/92/attachments/original/1518443729/Momentum_logo_for_emails.png?1518443729 as the URL of an image to insert the Momentum logo.'),
        ),
    ]
