# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-18 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxv', '0003_auto_20180508_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
