# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-23 07:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxv', '0004_email_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', django.contrib.postgres.fields.citext.CIEmailField(max_length=255, unique=True)),
                ('reconsented_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
