# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-23 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxv', '0005_reconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconsent',
            name='email_preset',
            field=models.BooleanField(default=False),
        ),
    ]
