# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-23 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mxv', '0006_reconsent_email_preset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reconsent',
            name='email_preset',
        ),
    ]
