# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-23 13:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mxv', '0009_auto_20180523_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconsent',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(max_length=255, unique=True),
        ),
    ]
