# Generated by Django 3.0.6 on 2020-06-04 14:38

from django.db import migrations, models
import django.db.models.deletion
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.Category'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(help_text='Maximum 200 words', max_length=2048, validators=[questions.models.answer_length]),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='Maximum 40 words', max_length=255, validators=[questions.models.question_length]),
        ),
    ]
