# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-24 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='display_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
