# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-29 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_choice_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='guidance',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
