# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-22 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_question_guidance'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='redirect_url',
            field=models.TextField(default=''),
        ),
    ]
