# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-29 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_choice_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='post_questions_text',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pre_questions_text',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='visible_to_non_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='template',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
