# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-29 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_auto_20181029_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='display_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
