# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-29 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0008_auto_20181029_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='redirect_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
