# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-15 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0010_consultation_hide_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='guidance',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
