# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='proposal_deadline',
            new_name='submission_deadline',
        ),
    ]
