# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20180104_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
