# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20180104_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='display_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='track',
            name='display_order',
            field=models.IntegerField(default=1),
        ),
    ]
