# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_track_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
