# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_proposal_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='amendment',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
