# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_amendment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='nomination_deadline',
        ),
        migrations.RemoveField(
            model_name='track',
            name='start',
        ),
        migrations.RemoveField(
            model_name='track',
            name='submission_deadline',
        ),
        migrations.AddField(
            model_name='track',
            name='allow_member_proposals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='track',
            name='allow_voting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='track',
            name='submission_end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='submission_start',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='voting_end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='voting_start',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
