# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_auto_20180119_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='description',
        ),
    ]
