# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_theme_guidance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='allow_voting',
            new_name='allow_nominations',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='voting_end',
            new_name='nomination_end',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='voting_start',
            new_name='nomination_start',
        ),
    ]
