# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0013_proposalurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='allow_member_proposals',
            new_name='allow_submissions',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='views',
        ),
    ]
