# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 17:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0015_auto_20180123_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(default='', max_length=4000)),
                ('amendment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_requests', to='review.Amendment')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=4000),
        ),
        migrations.AddField(
            model_name='moderationrequest',
            name='comment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_requests', to='review.Comment'),
        ),
        migrations.AddField(
            model_name='moderationrequest',
            name='proposal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_requests', to='review.Proposal'),
        ),
        migrations.AddField(
            model_name='moderationrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
