# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0018_moderationrequest_moderated'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalurl',
            name='external',
            field=models.BooleanField(default=False),
        ),
    ]
