# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0019_proposalurl_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='track',
            name='guidance',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
