# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-16 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0022_remove_track_guidance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='urgent',
        ),
    ]
