# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-26 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0023_remove_track_urgent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackVoting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_start', models.DateField(blank=True, default=None, null=True)),
                ('voting_end', models.DateField(blank=True, default=None, null=True)),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='review.Track')),
            ],
        ),
        migrations.RemoveField(
            model_name='amendmenthistory',
            name='amendment',
        ),
        migrations.RemoveField(
            model_name='proposalhistory',
            name='proposal',
        ),
        migrations.DeleteModel(
            name='AmendmentHistory',
        ),
        migrations.DeleteModel(
            name='ProposalHistory',
        ),
    ]
