# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-26 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0025_auto_20180226_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackvoting',
            name='template',
            field=models.CharField(default='', max_length=100),
        ),
    ]
