# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-15 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='job_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
