# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-25 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20190416_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaiseExceptionTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.Task')),
            ],
            bases=('tasks.task',),
        ),
    ]
