# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-26 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_raiseexceptiontask'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingintentiontagtask',
            name='maximum_attempts',
            field=models.IntegerField(default=50),
        ),
    ]
