# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-27 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_votingintentiontagtask_maximum_attempts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votingintentiontagtask',
            old_name='maximum_attempts',
            new_name='maximum_runtime',
        ),
    ]
