# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-27 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20190427_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='repeat_count',
            field=models.IntegerField(blank=True, default=None, help_text='How many times to repeat (leave blank for indefinitely)', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='repeat_seconds',
            field=models.IntegerField(blank=True, default=None, help_text='How often to repeat in seconds (leave blank to run only once)', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(blank=True, default=None, help_text='Time of first run (leave blank to run immediately)', null=True),
        ),
        migrations.AlterField(
            model_name='votingintentiontagtask',
            name='maximum_runtime',
            field=models.IntegerField(default=50, help_text='Maximum runtime in seconds'),
        ),
    ]
