# Generated by Django 3.0.6 on 2020-06-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20190427_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raiseexceptiontask',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='sendemailtask',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='votingintentiontagtask',
            options={'base_manager_name': 'objects'},
        ),
    ]
