# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-10 17:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_intentions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intention',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(max_length=255, verbose_name='email address'),
        ),
    ]
