# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-11 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_intentions', '0002_auto_20180710_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlparameter',
            name='pass_on_name',
            field=models.TextField(default=''),
        ),
    ]
