# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-11 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting_intentions', '0003_urlparameter_pass_on_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_tags', to='voting_intentions.Choice')),
            ],
        ),
        migrations.CreateModel(
            name='VoteTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_tags', to='voting_intentions.Vote')),
            ],
        ),
    ]
