# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-11 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_intentions', '0004_choicetag_votetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='intention',
            name='nation_builder_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
