# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-20 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_intentions', '0005_intention_nation_builder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicetag',
            name='add',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='votetag',
            name='add',
            field=models.BooleanField(default=True),
        ),
    ]
