# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-20 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_intentions', '0006_auto_20180720_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='redirect_url',
            field=models.TextField(default=''),
        ),
    ]
