# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-20 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_intentions', '0007_choice_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='intention',
            name='tags_written_to_nation_builder',
            field=models.BooleanField(default=False),
        ),
    ]
