# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-25 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_intentions', '0009_intention_email_unknown_in_nation_builder'),
    ]

    operations = [
        migrations.AddField(
            model_name='intention',
            name='tags_processed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
