# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-26 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_intentions', '0010_intention_tags_processed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intention',
            name='email_unknown_in_nation_builder',
            field=models.NullBooleanField(default=None),
        ),
    ]
