# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-26 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_intentions', '0011_auto_20190426_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intention',
            old_name='tags_processed_at',
            new_name='processed_at',
        ),
    ]
