# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-29 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_intentions', '0012_auto_20190426_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
