# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-30 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_intentions', '0016_auto_20190430_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='redirect_url',
            field=models.CharField(max_length=100),
        ),
    ]
