# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-30 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_intentions', '0017_auto_20190430_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='redirect_url',
            field=models.CharField(blank=True, default=None, help_text='Set this to override the redirect for this choice', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='choicetag',
            name='add',
            field=models.BooleanField(default=True, help_text='Clear this to remove the tag instead'),
        ),
        migrations.AlterField(
            model_name='choicetag',
            name='text',
            field=models.CharField(help_text='The tag to add to NationBuilder for this choice', max_length=100),
        ),
        migrations.AlterField(
            model_name='urlparameter',
            name='name',
            field=models.CharField(help_text='The name of the URL parameter to pass on when redirecting', max_length=100),
        ),
        migrations.AlterField(
            model_name='urlparameter',
            name='pass_on_name',
            field=models.CharField(blank=True, default=None, help_text='Set this to pass the parameter on with a different name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='redirect_url',
            field=models.CharField(help_text='Redirects here after voting (unless a choice-level redirect is set)', max_length=100),
        ),
        migrations.AlterField(
            model_name='votetag',
            name='add',
            field=models.BooleanField(default=True, help_text='Clear this to remove the tag instead'),
        ),
        migrations.AlterField(
            model_name='votetag',
            name='text',
            field=models.CharField(help_text='The tag to add to NationBuilder for this vote', max_length=100),
        ),
    ]
