# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-30 10:31
from __future__ import unicode_literals

from django.db import migrations

# populates NationBuilder values for known URL parameters
def populate_nation_builder_values(apps, schema_editor):
    
    # get the URL parameter model
    UrlParameter = apps.get_model('voting_intentions', 'UrlParameter')
    
    # set known URL parameter values
    for param in UrlParameter.objects.all():
        if param.name == 'email':
            param.nation_builder_value = '{{ recipient.email }}'
        if param.name == 'donation_first_name':
            param.nation_builder_value = '{{ recipient.first_name }}'
        if param.name == 'donation_last_name':
            param.nation_builder_value = '{{ recipient.last_name }}'
        param.save()


class Migration(migrations.Migration):

    dependencies = [
        ('voting_intentions', '0019_urlparameter_nation_builder_value'),
    ]

    operations = [
        migrations.RunPython(populate_nation_builder_values),
    ]
