# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-22 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_intentions', '0021_defaulturlparameter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultUrlParameter',
        ),
    ]
