# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 09:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20171215_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentumGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='is_ncg',
            field=models.BooleanField(default=False, verbose_name='NCG'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_ncg_officer',
            field=models.BooleanField(default=False, verbose_name='NCG officer (can act on behalf of NCG)'),
        ),
        migrations.AddField(
            model_name='momentumgroup',
            name='primary_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='momentum_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='members.MomentumGroup'),
        ),
    ]
