# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20180123_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_invited_to_activate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
