# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_member_last_invited_to_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberactivationemail',
            name='send_count',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
