# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-28 17:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_memberactivationemail_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
