# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-29 11:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20180228_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', django.contrib.postgres.fields.citext.CIEmailField(max_length=255, unique=True)),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
    ]
