# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-08 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20180329_1248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTarget',
        ),
        migrations.DeleteModel(
            name='MemberActivationEmail',
        ),
    ]
