# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-17 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20180508_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='last_invited_to_activate',
            new_name='last_emailed',
        ),
    ]
