# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 10:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20180517_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momentumgroup',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
