# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-21 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20190721_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membereditablenationbuilderfield',
            name='field_type',
            field=models.CharField(choices=[('Char', 'Single line text'), ('Integer', 'Integer'), ('Decimal', 'Decimal'), ('Boolean', 'Checkbox (true/false)'), ('Email', 'Email')], default=members.models.MemberEditableFieldType('Single line text'), max_length=8),
        ),
    ]
