# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-20 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20190720_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='membereditablenationbuilderfield',
            name='admin_only',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membereditablenationbuilderfield',
            name='display_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='membereditablenationbuilderfield',
            name='display_text',
            field=models.CharField(default='field', max_length=255),
        ),
        migrations.AddField(
            model_name='membereditablenationbuilderfield',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membereditablenationbuilderfield',
            name='field_type',
            field=models.CharField(choices=[(members.models.MemberEditableFieldType('Single line text'), 'Single line text'), (members.models.MemberEditableFieldType('Multiple line text'), 'Multiple line text'), (members.models.MemberEditableFieldType('Integer'), 'Integer'), (members.models.MemberEditableFieldType('Decimal'), 'Decimal'), (members.models.MemberEditableFieldType('Checkbox (true/false)'), 'Checkbox (true/false)'), (members.models.MemberEditableFieldType('Email'), 'Email'), (members.models.MemberEditableFieldType('Date'), 'Date'), (members.models.MemberEditableFieldType('Time'), 'Time'), (members.models.MemberEditableFieldType('Date and time'), 'Date and time')], max_length=8),
        ),
    ]
