# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-20 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_auto_20190720_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membereditablenationbuilderfield',
            name='display_text',
            field=models.CharField(default='', max_length=255),
        ),
    ]
