# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-22 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_auto_20190818_1651'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberEditableNationBuilderField',
            new_name='ProfileField',
        ),
    ]
