# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-22 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20190822_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateDetailsCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_page_pre_text', models.TextField()),
                ('first_page_post_text', models.TextField()),
                ('second_page_pre_text', models.TextField()),
                ('second_page_post_text', models.TextField()),
                ('redirect_URL', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
