# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-20 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20190720_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membereditablenationbuilderfield',
            name='field_type',
            field=models.CharField(choices=[(members.models.MemberEditableFieldType('Single line text'), 'Single line text'), (members.models.MemberEditableFieldType('Multiple line text'), 'Multiple line text'), (members.models.MemberEditableFieldType('Integer'), 'Integer'), (members.models.MemberEditableFieldType('Decimal'), 'Decimal'), (members.models.MemberEditableFieldType('Checkbox (true/false)'), 'Checkbox (true/false)'), (members.models.MemberEditableFieldType('Email'), 'Email'), (members.models.MemberEditableFieldType('Date'), 'Date'), (members.models.MemberEditableFieldType('Time'), 'Time'), (members.models.MemberEditableFieldType('Date and time'), 'Date and time')], default=members.models.MemberEditableFieldType('Single line text'), max_length=8),
        ),
    ]
