# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-22 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_campaignfield_campaigntag'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntag',
            name='display_order',
            field=models.IntegerField(default=1),
        ),
    ]
