# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-23 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_urlparameter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updatedetailscampaign',
            old_name='redirect_URL',
            new_name='redirect_url',
        ),
    ]
