# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-23 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_auto_20190823_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaigntag',
            old_name='label',
            new_name='display_text',
        ),
    ]
