# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-28 10:32
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_auto_20190823_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationBuilderPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', django.contrib.postgres.fields.citext.CIEmailField(max_length=255, unique=True)),
                ('unique_token', models.CharField(default=members.models.activation_key_default, max_length=20)),
                ('nation_builder_id', models.IntegerField(blank=True, default=None, null=True)),
                ('member', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nation_builder_person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
