# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-28 10:33
from __future__ import unicode_literals

from django.db import migrations

# creates NationBuilderPerson records for existing members
def create_nation_builder_persons(apps, schema_editor):
    Member = apps.get_model('members', 'Member')
    NationBuilderPerson = apps.get_model('members', 'NationBuilderPerson')
    for member in Member.objects.all():
        NationBuilderPerson.objects.using(schema_editor.connection.alias).create(member = member, nation_builder_id = member.nation_builder_id, email = member.email)

# deletes all NationBuilderPerson records
def delete_nation_builder_persons(apps, schema_editor):
    NationBuilderPerson = apps.get_model('members', 'NationBuilderPerson')
    NationBuilderPerson.objects.using(schema_editor.connection.alias).all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_nationbuilderperson'),
    ]

    operations = [
        migrations.RunPython(create_nation_builder_persons, delete_nation_builder_persons)
    ]
