# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-29 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_remove_member_nation_builder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationbuilderperson',
            name='unique_token',
            field=models.CharField(default=members.models.unused_unique_token, max_length=20),
        ),
    ]
