# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-30 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_auto_20190829_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignfield',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaignfield',
            name='profilefield_ptr',
        ),
        migrations.DeleteModel(
            name='CampaignField',
        ),
    ]
