# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-30 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_auto_20190830_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_path', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('Char', 'Single line text'), ('Integer', 'Integer'), ('Decimal', 'Decimal'), ('Boolean', 'Checkbox (true/false)'), ('Email', 'Email')], default=members.models.ProfileFieldType('Single line text'), max_length=8)),
                ('required', models.BooleanField(default=False)),
                ('display_text', models.CharField(default='', max_length=255)),
                ('display_order', models.IntegerField(default=1)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='members.UpdateDetailsCampaign')),
            ],
        ),
    ]
