# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-30 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_campaignfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignfield',
            name='display_order',
            field=models.IntegerField(default=members.models.campaign_field_next_display_order),
        ),
        migrations.AlterField(
            model_name='campaigntag',
            name='display_order',
            field=models.IntegerField(default=members.models.campaign_tag_next_display_order),
        ),
    ]
