# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-30 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0031_auto_20190830_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefield',
            name='display_order',
            field=models.IntegerField(default=members.models.profile_field_next_display_order),
        ),
    ]
