# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-31 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_auto_20190831_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updatedetailscampaign',
            old_name='second_page_post_text',
            new_name='fields_page_footer',
        ),
        migrations.RenameField(
            model_name='updatedetailscampaign',
            old_name='second_page_pre_text',
            new_name='fields_page_header',
        ),
    ]
