# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-02 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0033_auto_20190831_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignfield',
            name='matching_url_parameter_name',
            field=models.CharField(default='', help_text='The name of the matching URL parameter to update when this field changes', max_length=100),
        ),
    ]
