# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-02 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0037_auto_20190902_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlparameter',
            name='default_value_if_no_nation_builder_value',
            field=models.CharField(blank=True, default=None, help_text='The value for this parameter if NationBuilder does not supply one', max_length=100, null=True),
        ),
    ]
