# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-03 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0038_auto_20190902_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignfield',
            name='is_phone_number',
            field=models.BooleanField(default=False),
        ),
    ]
